#!/bin/zsh

#################################################################
# Environment variables and options

# XDG base directory specs
export XDG_CACHE_HOME="$HOME/.cache"                    # user non-essential (cached) data
export XDG_CONFIG_DIRS=                                 # search dirs for configs
export XDG_CONFIG_HOME="$HOME/.config"                  # user configs
export XDG_DATA_DIRS='/usr/local/share/:/usr/share/'    # search dirs for data
export XDG_DATA_HOME="$HOME/.local/share"               # user data
export XDG_RUNTIME_DIR=                                 # user runtime files
export XDG_SESSION_CLASS=                               #
export XDG_SESSION_ID=                                  #
export XDG_SESSION_TYPE=                                #
export XDG_STATE_HOME="$HOME/.local/state"              # user state data (logs, hist, ...)

# Update PATH
# VS code says this should be in ~/.zprofile
VSCODE_CLI='/Applications/Visual Studio Code.app/Contents/Resources/app/bin' # add vscode CLI 'code'
for directory in "$VSCODE_CLI"; do
    [[ ":$PATH:" == *:"$directory":* ]] && break
    [ -d "$directory" ] || {
        echo "$directory doesn't exist"
        exit 1
    }
    PATH="$PATH:$directory"
done                                                        # add to PATH
for directory in ${(s/:/)PATH}; do
    [[ ":$newpath:" != *:"$directory":* ]] \
        && newpath="${newpath}:${directory}" \
        || true
done                                                        # rm dups
PATH=$(echo "$newpath" | sed 's/^:*//; s/:*$//; s/::/:/g')  # rm leading, trailing ':' seps
export PATH

# Configure bash
# Vars
export CDPATH='.:~/:..:../..'                           # dirs for 'cd' to search
export HISTSIZE=100000                                  # max cmds
export HISTFILESIZE=100000                              # max lines
export HOSTFILE='/etc/hosts'                            # use for hostname completion
export LESSHISTFILE="$XDG_STATE_HOME/less/history"      # ~/.lesshst
mkdir -p "$XDG_STATE_HOME/less"
export MANWIDTH=80                                      # manpage width, use < 80 if COLUMNS=80 & less -N
# Options
# option names are case-insensitive and underscores are ignored
setopt AUTO_CD                  # if unrecognized cmd is dir in interactive shell, do 'cd <dir>'
setopt CORRECT                  # fix cmd types
setopt CORRECT_ALL              # fix arg types
setopt DOT_GLOB                 # include '.*' in results of filename expansion
setopt HIST_FIND_NO_DUPS        # no dups, even if dups aren't contiguous
setopt HIST_IGNORE_DUPS         # omit dups
setopt HIST_IGNORE_SPACE        # omit lines starting w spaces
setopt HIST_VERIFY              # ['readline'] substitutions routed 'readline' -> shell parser
setopt INC_APPEND_HISTORY       # add immediately (not on exit) & append, don't overwrite on exit
setopt INTERACTIVE_COMMENTS     # allow comments in interactive shell
setopt NO_CLOBBER               # disallow ‘>’ redirection to overwrite
setopt RM_STAR_WAIT             # on ‘rm *’ or ‘rm path/*’, prompt, wait 10s, and ignore anything typed

# Configure editor
export VISUAL='vi'
if [ "$VSCODE_INJECTION" = "1" ] && command -v code > /dev/null; then
    export VISUAL='code --wait'
fi
export EDITOR="$VISUAL"

# Configure readline
bindkey "\C-i": menu-complete                       # Cycle through ambiguous completions instead of list
bindkey "\e[1;3C" forward-word                      # Ctrl-right-arrow = word moving forward
bindkey "\e[1;3D" backward-word                     # Ctrl-left-arrow = word moving backward
bindkey "\e[A" history-beginning-search-backward    # up arrow = move up
bindkey "\e[B" history-beginning-search-forward     # down arrow = move down
bindkey "^[[1;9C" end-of-line                       #
bindkey "^[[1;9D" beginning-of-line                 #
bindkey "^R" history-incremental-search-backward    # Ctrl-R = search history
# ref: https://code.visualstudio.com/docs/terminal/basics#_ctrla-ctrlr-output-a-r-on-zsh
bindkey -e                                          # set Emacs

#################################################################
# Aliases

# Aliases
alias ...='cd ../..'
alias ..='cd ..'
# shellcheck disable=SC2139,SC2086
alias edit=$VISUAL
alias grep='grep --color=always'
alias ll='ls -lahF'
alias mv='mv -i'
alias rm='rm -i'

# Executed when shell exits (login or interactive)
TRAPEXIT() {
    if [[ ! -o login ]]; then
        . ~/.zlogout
    fi
}