# /etc/krb5.conf -- Kerberos V5 general configuration.
# 
# Troubleshooting
# https://docs.mpcdf.mpg.de/doc/data/store/troubleshooting/troubleshooting.html 
# 
# The AFS cell “ipp-garching.mpg.de” will therefore be set to read-only at 
# the end of November 2025 and will be finally shut down in November 2026.
# https://docs.mpcdf.mpg.de/bnb/219.html#a-farewell-to-the-afs-cell-ipp-garching-mpg-de


[libdefaults]
    default_realm           = IPP-GARCHING.MPG.DE
    clockskew               = 300
    ticket_lifetime         = 25h
    renew_lifetime          = 7d
    v4_instance_resolve     = false
    forwardable             = true
    forward                 = true
    proxiable               = true

[realms]
    IPP-GARCHING.MPG.DE = {
        kdc                 = kerberos1.rzg.mpg.de
        kdc                 = kerberos2.rzg.mpg.de
        kdc                 = kerberos3.rzg.mpg.de
        admin_server        = kerberos1.rzg.mpg.de
    }

[domain_realm]
    mpcdf.mpg.de            = IPP-GARCHING.MPG.DE
    .mpcdf.mpg.de           = IPP-GARCHING.MPG.DE
    rzg.mpg.de              = IPP-GARCHING.MPG.DE
    .rzg.mpg.de             = IPP-GARCHING.MPG.DE
    ipp.mpg.de              = IPP-GARCHING.MPG.DE
    .ipp.mpg.de             = IPP-GARCHING.MPG.DE
    ipp-hgw.mpg.de          = IPP-GARCHING.MPG.DE
    .ipp-hgw.mpg.de         = IPP-GARCHING.MPG.DE
    ipp-garching.mpg.de     = IPP-GARCHING.MPG.DE
    .ipp-garching.mpg.de    = IPP-GARCHING.MPG.DE